apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-homelab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@codeberg.org:terminalnode/k8s-homelab.git
    targetRevision: HEAD
    path: homelab
  destination:
    server: https://kubernetes.default.svc
    namespace: homelab
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
