apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: asciinema
  namespace: argocd
spec:
  description: 'App for Asciinema'
  sourceRepos:
  - 'git@codeberg.org:terminalnode/k8s-homelab.git'
  - 'https://operator.min.io'
  destinations:
  - server: 'https://kubernetes.default.svc'
    namespace: asciinema

---

apiVersion: v1
kind: Namespace
metadata:
  name: asciinema

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: asciinema
  namespace: argocd
spec:
  project: asciinema
  sources:
  - repoURL: git@codeberg.org:terminalnode/k8s-homelab.git
    targetRevision: HEAD
    path: manifests/asciinema/asciinema
  destination:
    server: https://kubernetes.default.svc
    namespace: asciinema
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: asciinema-db
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: asciinema
  sources:
  - repoURL: git@codeberg.org:terminalnode/k8s-homelab.git
    targetRevision: HEAD
    path: manifests/asciinema/asciinema-db
  destination:
    server: https://kubernetes.default.svc
    namespace: asciinema
  syncPolicy:
    syncOptions:
    - PreserveResourcesOnDeletion=true
    automated:
      selfHeal: true
      prune: false
