apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: freshrss
  namespace: argocd
spec:
  description: 'Apps for FreshRSS'
  sourceRepos:
  - 'git@codeberg.org:terminalnode/k8s-homelab.git'
  destinations:
  - server: 'https://kubernetes.default.svc'
    namespace: freshrss

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: freshrss
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link: 'https://rss.termz.xyz/'
spec:
  project: freshrss
  source:
    repoURL: git@codeberg.org:terminalnode/k8s-homelab.git
    targetRevision: HEAD
    path: manifests/freshrss/freshrss
  destination:
    server: https://kubernetes.default.svc
    namespace: freshrss
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: freshrss-db
  namespace: argocd
spec:
  project: freshrss
  source:
    repoURL: git@codeberg.org:terminalnode/k8s-homelab.git
    targetRevision: HEAD
    path: manifests/freshrss/freshrss-db
  destination:
    server: https://kubernetes.default.svc
    namespace: freshrss
  syncPolicy:
    syncOptions:
    - PreserveResourcesOnDeletion=true
    automated:
      selfHeal: true
      prune: false
