apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gwainet
  namespace: argocd
spec:
  description: 'Apps for GwaiNet'
  clusterResourceWhitelist:
  - group: 'cert-manager.io'
    kind: 'ClusterIssuer'
  sourceRepos:
  - 'git@codeberg.org:terminalnode/k8s-homelab.git'
  destinations:
  - server: 'https://kubernetes.default.svc'
    namespace: gwainet
  - server: 'https://kubernetes.default.svc'
    namespace: cert-manager

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gwaidns
  namespace: argocd
spec:
  project: gwainet
  source:
    repoURL: git@codeberg.org:terminalnode/k8s-homelab.git
    targetRevision: HEAD
    path: manifests/gwainet/gwaidns
  destination:
    server: https://kubernetes.default.svc
    namespace: gwainet
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gwai-ca
  namespace: argocd
spec:
  project: gwainet
  source:
    repoURL: git@codeberg.org:terminalnode/k8s-homelab.git
    targetRevision: HEAD
    path: manifests/gwainet/gwai-ca
  destination:
    server: https://kubernetes.default.svc
    namespace: gwainet
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
