apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: 'Resources related to running the cluster'
  clusterResourceWhitelist:
  - group: 'cert-manager.io'
    kind: '*'
  - group: 'storage.k8s.io'
    kind: '*'
  - group: 'apiextensions.k8s.io'
    kind: '*'
  - group: 'rbac.authorization.k8s.io'
    kind: '*'
  - group: 'admissionregistration.k8s.io'
    kind: '*'
  sourceRepos:
  - 'git@codeberg.org:terminalnode/k8s-homelab.git'
  - 'https://charts.jetstack.io'
  - 'https://cloudnative-pg.github.io/charts'
  destinations:
  - server: 'https://kubernetes.default.svc'
    namespace: infrastructure
  - server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  - server: 'https://kubernetes.default.svc'
    namespace: kube-system
  - server: 'https://kubernetes.default.svc'
    namespace: argocd
  - server: 'https://kubernetes.default.svc'
    namespace: cnpg-system

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: letsencrypt
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: git@codeberg.org:terminalnode/k8s-homelab.git
    targetRevision: HEAD
    path: manifests/infrastructure/letsencrypt
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusterconfig
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: git@codeberg.org:terminalnode/k8s-homelab.git
    targetRevision: HEAD
    path: manifests/infrastructure/clusterconfig
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.18.0
    helm:
      values: |
        installCRDs: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: 'https://cloudnative-pg.github.io/charts'
    chart: cloudnative-pg
    targetRevision: '0.24.0' 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'cnpg-system' 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: git@codeberg.org:terminalnode/k8s-homelab.git
    targetRevision: HEAD
    path: manifests/infrastructure/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
