apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: miniflux
  namespace: argocd
spec:
  description: 'App for Miniflux'
  sourceRepos:
  - 'git@codeberg.org:terminalnode/k8s-homelab.git'
  destinations:
  - server: 'https://kubernetes.default.svc'
    namespace: miniflux

---

apiVersion: v1
kind: Namespace
metadata:
  name: miniflux

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniflux
  namespace: argocd
spec:
  project: miniflux
  source:
    repoURL: git@codeberg.org:terminalnode/k8s-homelab.git
    targetRevision: HEAD
    path: manifests/miniflux/miniflux
  destination:
    server: https://kubernetes.default.svc
    namespace: miniflux
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniflux-db
  namespace: argocd
spec:
  project: miniflux
  source:
    repoURL: git@codeberg.org:terminalnode/k8s-homelab.git
    targetRevision: HEAD
    path: manifests/miniflux/miniflux-db
  destination:
    server: https://kubernetes.default.svc
    namespace: miniflux
  syncPolicy:
    syncOptions:
    - PreserveResourcesOnDeletion=true
    automated:
      selfHeal: true
      prune: false
