apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: miniflux
  namespace: argocd
spec:
  description: 'App for Miniflux'
  sourceRepos:
  - 'git@codeberg.org:terminalnode/k8s-homelab.git'
  - 'https://operator.min.io'
  destinations:
  - server: 'https://kubernetes.default.svc'
    namespace: miniflux
  - server: 'https://kubernetes.default.svc'
    namespace: argocd

---

apiVersion: v1
kind: Namespace
metadata:
  name: miniflux

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniflux
  namespace: argocd
spec:
  project: miniflux
  source:
    repoURL: git@codeberg.org:terminalnode/k8s-homelab.git
    targetRevision: HEAD
    path: manifests/miniflux/miniflux
  destination:
    server: https://kubernetes.default.svc
    namespace: miniflux
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniflux-db
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: miniflux
  sources:
    - repoURL: git@codeberg.org:terminalnode/k8s-homelab.git
      targetRevision: HEAD
      path: manifests/miniflux/miniflux-db
  destination:
    server: https://kubernetes.default.svc
    namespace: miniflux
  syncPolicy:
    syncOptions:
    - PreserveResourcesOnDeletion=true
    automated:
      selfHeal: true
      prune: false

# ---
# 
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: miniflux-db-minio
#   namespace: argocd
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   project: miniflux
#   sources:
#     - repoURL: 'https://operator.min.io'
#       chart: tenant
#       targetRevision: '7.1.1'
#       helm:
#         valuesObject:
#           tenant:
#             name: "miniflux-db-minio-tenant"
#           spec:
#             name:  "miniflux-db-minio"
#             pools:
#             - name: "pool-0"
#               servers: 4
#               volumesPerServer: 2
#               size: "1Gi"
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: miniflux
#   syncPolicy:
#     syncOptions:
#     - PreserveResourcesOnDeletion=true
#     automated:
#       selfHeal: true
#       prune: false
