apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: photon
  name: photon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: photon
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: photon
    spec:
      containers:
      - image: ghcr.io/xyphyn/photon:v1.31.4
        name: photon
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: photon
spec:
  selector:
    app: photon
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
