apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: photon
  name: photon-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photon
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: photon
    spec:
      containers:
      - image: ghcr.io/xyphyn/photon:v1.31.4
        name: photon
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: photon-service
spec:
  selector:
    app: photon
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: photon-ingress
spec:
  rules:
    - host: phtn.termz.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: photon-service
                port:
                  number: 80
    - host: phtn.terminalnode.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: photon-service
                port:
                  number: 80
