apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: miniflux-cluster
  labels:
    app: miniflux
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  serviceAccountTemplate:
    metadata:
      name: 'miniflux-cnpg-sa'
  bootstrap:
    initdb:
      database: miniflux
      owner: miniflux
      encoding: UTF8
  storage:
    size: 2Gi
    storageClass: local-path
  backup:
    barmanObjectStore:
      destinationPath: 's3://miniflux-db-backups/'
      endpointURL: http://miniflux-tenant-hl.miniflux:9000
      s3Credentials:
        accessKeyId:
          name: miniflux-tenant-conf-secret
          key: MINIO_ROOT_USER
        secretAccessKey:
          name: miniflux-tenant-conf-secret
          key: MINIO_ROOT_PASSWORD
      wal:
        compression: gzip
      data:
        compression: gzip
