apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    app: freshrss
  name: freshrss-cluster
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  bootstrap:
    initdb:
      database: freshrss
      owner: freshrss
      encoding: UTF8
  storage:
    size: 1Gi
    storageClass: local-path
