apiVersion: v1
kind: Service
metadata:
  name: gwaidns-1-lb
  labels:
    app.kubernetes.io/name: gwaidns
    app.kubernetes.io/instance: gwaidns-1
    app.kubernetes.io/component: coredns
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: gwaidns
    app.kubernetes.io/instance: gwaidns-1
    app.kubernetes.io/component: coredns
  ports:
  - port: 53
    targetPort: 53
    protocol: UDP

---

apiVersion: v1
kind: Service
metadata:
  name: gwaidns-2-lb
  labels:
    app.kubernetes.io/name: gwaidns
    app.kubernetes.io/instance: gwaidns-2
    app.kubernetes.io/component: coredns
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: gwaidns
    app.kubernetes.io/instance: gwaidns-2
    app.kubernetes.io/component: coredns
  ports:
  - port: 53
    targetPort: 53
    protocol: UDP
