apiVersion: v1
kind: Service
metadata:
  name: gwaidns-1-svc
  labels:
    app.kubernetes.io/name: gwaidns
    app.kubernetes.io/instance: gwaidns-1
    app.kubernetes.io/component: coredns
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: gwaidns
    app.kubernetes.io/instance: gwaidns-1
    app.kubernetes.io/component: coredns
  ports:
  - name: "udp"
    protocol: UDP
    port: 53
    targetPort: 53
    nodePort: 30053
  - name: "tcp"
    port: 53
    protocol: TCP
    targetPort: 53
    nodePort: 31053

---

apiVersion: v1
kind: Service
metadata:
  name: gwaidns-2-svc
  labels:
    app.kubernetes.io/name: gwaidns
    app.kubernetes.io/instance: gwaidns-2
    app.kubernetes.io/component: coredns
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: gwaidns
    app.kubernetes.io/instance: gwaidns-2
    app.kubernetes.io/component: coredns
  ports:
  - name: "udp"
    protocol: UDP
    port: 53
    targetPort: 53
    nodePort: 30054
  - name: "tcp"
    port: 53
    protocol: TCP
    targetPort: 53
    nodePort: 31054
