apiVersion: v1
kind: Service
metadata:
  name: gwaidns-svc
  labels:
    app: gwaidns
spec:
  type: NodePort
  selector:
    app: gwaidns
  ports:
  - name: "udp"
    protocol: UDP
    port: 53
    targetPort: 53
  - name: "tcp"
    port: 53
    protocol: TCP
    targetPort: 53
