apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: freshrss
  name: freshrss-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: freshrss
    spec:
      containers:
      - image: docker.io/freshrss/freshrss:1.26.3-alpine
        name: freshrss
        envFrom:
        - configMapRef:
            name: freshrss-cm
        env:
        - name: TRUSTED_PROXY
          value: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
        - name: ADMIN_EMAIL
          value: 'alex@gwai.se'
        - name: DB_HOST
          value: 'freshrss-cluster-rw'
        - name: DB_BASE
          value: 'freshrss'
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: 'freshrss-cluster-app'
              key: 'username'
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: 'freshrss-cluster-app'
              key: 'password'
        - name: FRESHRSS_INSTALL
          value: |-
            --api-enabled
            --db-base freshrss
            --db-host $(DB_HOST)
            --db-password $(DB_PASSWORD)
            --db-type pgsql
            --db-user $(DB_USER)
            --default-user alex
        #    --password password
        - name: FRESHRSS_USER
          value: |-
            --user alex
            --email alex@gwai.se
            --language en
        ports:
        - containerPort: 80
