apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freshrss-ingress
  labels:
    app: freshrss
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-ciss"
    kubernetes.io/ingress.class: "traefik" 
spec:
  tls:
  - hosts:
    - rss.termz.xyz
    - rss.terminalnode.xyz
    secretName: freshrss-tls-secret
  rules:
  - host: "rss.termz.xyz"
    http: &http-routing
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: freshrss-svc
            port:
              number: 80
  - host: "rss.terminalnode.xyz"
    http: *http-routing

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freshrss-dot-gwai-ingress
  labels:
    app: freshrss
  annotations:
    cert-manager.io/cluster-issuer: "dot-gwai-ciss"
    cert-manager.io/common-name: "Gwainet FreshRSS Service"
    kubernetes.io/ingress.class: "traefik" 
spec:
  tls:
  - hosts:
    - rss.gwai
    secretName: dot-gwai-ca-secret
  rules:
  - host: "rss.gwai"
    http: &http-routing
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: freshrss-svc
            port:
              number: 80
