apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: asciinema-cluster
  labels:
    app: asciinema
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  serviceAccountTemplate:
    metadata:
      name: 'asciinema-cnpg-sa'
  bootstrap:
    initdb:
      database: asciinema
      owner: asciinema
      encoding: UTF8
  storage:
    size: 2Gi
    storageClass: local-path
  backup:
    barmanObjectStore:
      destinationPath: 's3://asciinema-db-backups/'
      endpointURL: http://asciinema-tenant-hl.asciinema:9000
      s3Credentials:
        accessKeyId:
          name: asciinema-tenant-conf-secret
          key: MINIO_ROOT_USER
        secretAccessKey:
          name: asciinema-tenant-conf-secret
          key: MINIO_ROOT_PASSWORD
      wal:
        compression: gzip
      data:
        compression: gzip
