apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: asciinema-cluster-scheduled-backup
  labels:
    app: asciinema
spec:
  schedule: "0 40 4 * * *"
  backupOwnerReference: self
  method: barmanObjectStore
  cluster:
    name: asciinema-cluster
