apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: readeck-cluster
  labels:
    app: readeck
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  serviceAccountTemplate:
    metadata:
      name: 'readeck-cnpg-sa'
  bootstrap:
    initdb:
      database: readeck
      owner: readeck
      encoding: UTF8
  storage:
    size: 2Gi
    storageClass: local-path
  backup:
    barmanObjectStore:
      destinationPath: 's3://readeck-db-backups/'
      endpointURL: http://readeck-tenant-hl.readeck:9000
      s3Credentials:
        accessKeyId:
          name: readeck-tenant-conf-secret
          key: MINIO_ROOT_USER
        secretAccessKey:
          name: readeck-tenant-conf-secret
          key: MINIO_ROOT_PASSWORD
      wal:
        compression: gzip
      data:
        compression: gzip
