apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-certificate
spec:
  secretName: argocd-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: argocd.termz.xyz
  dnsNames:
  - argocd.termz.xyz
  - argocd.terminalnode.xyz
