apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: asciinema
  name: asciinema-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asciinema
  template:
    metadata:
      labels:
        app: asciinema
    spec:
      serviceAccountName: asciinema-sa
      containers:
      - image: ghcr.io/asciinema/asciinema-server:latest
        name: asciinema
        envFrom:
        - secretRef:
            name: asciinema-smtp
            optional: true
        env:
        - name: SECRET_KEY_BASE
          value: sPQMZ57beqYeXF2xDUNwxqNf9SrEwfzukC7LXPvbGNSWczHPjYFnCEgQ2BCIRP0s
        - name: URL_HOST
          value: 'asciinema.shi.st'
        - name: URL_SCHEME
          value: 'https'
        - name: URL_PORT
          value: '80'
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: 'asciinema-cluster-app'
              key: 'username'
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: 'asciinema-cluster-app'
              key: 'password'
        - name: DATABASE_URL
          value: postgresql://$(DB_USER):$(DB_PASSWORD)@asciinema-cluster-rw/asciinema?sslmode=disable
        ports:
        - name: http
          containerPort: 4000
